// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone"], function(Backbone) {
    var ViewFirstModel;
    ViewFirstModel = (function(_super) {

      __extends(ViewFirstModel, _super);

      ViewFirstModel.instances = {};

      function ViewFirstModel(attributes) {
        var instances, model;
        instances = this.constructor.instances;
        if ((attributes != null ? attributes.id : void 0) != null) {
          if (instances[attributes.id] != null) {
            console.log("returning an existing instance");
            model = instances[attributes.id];
            Backbone.Model.apply(model, arguments);
            return model;
          }
          instances[attributes.id] = this;
        }
        Backbone.Model.apply(this, arguments);
      }

      return ViewFirstModel;

    })(Backbone.Model);
    return ViewFirstModel;
  });

}).call(this);
