// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone-relational", "backbone.localStorage", "backbone", "Collar"], function(BackboneRelational, BackboneLocalStorage, Backbone, Collar) {
    return window.Collars = (function(_super) {

      __extends(Collars, _super);

      function Collars() {
        return Collars.__super__.constructor.apply(this, arguments);
      }

      Collars.prototype.model = Collar;

      Collars.prototype.localStorage = new Store("DogModels");

      return Collars;

    })(Backbone.Collection);
  });

}).call(this);
