// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone-relational", "backbone.localStorage", "backbone", "Collar"], function(BackboneRelational, BackboneLocalStorage, Backbone, Collar) {
    return window.DogModel = (function(_super) {

      __extends(DogModel, _super);

      function DogModel() {
        return DogModel.__super__.constructor.apply(this, arguments);
      }

      DogModel.prototype.localStorage = new Store("DogModels");

      DogModel.prototype.url = "/";

      DogModel.prototype.relations = [
        {
          type: Backbone.HasOne,
          key: 'collar',
          relatedModel: 'Collar'
        }
      ];

      DogModel.prototype.defaults = {
        name: "",
        colour: "",
        breed: "",
        height: ""
      };

      DogModel.prototype.validate = function(attrs) {
        var errors;
        errors = [];
        if (!(attrs.age != null) || attrs.age === "") {
          errors.push({
            name: 'age',
            message: 'Age must be set'
          });
        }
        return false;
      };

      return DogModel;

    })(Backbone.RelationalModel);
  });

}).call(this);
