// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Item = (function(_super) {

    __extends(Item, _super);

    function Item() {
      return Item.__super__.constructor.apply(this, arguments);
    }

    Item.prototype.urlRoot = "/items";

    Item.prototype.defaults = {
      title: "",
      description: ""
    };

    return Item;

  })(window.ViewFirstModel);

  window.Items = (function(_super) {

    __extends(Items, _super);

    function Items() {
      return Items.__super__.constructor.apply(this, arguments);
    }

    Items.prototype.model = Item;

    Items.prototype.url = "/items";

    return Items;

  })(Backbone.Collection);

  window.allItems = new Items;

  window.allItems.fetch({
    success: function(collection) {
      return console.log("There are now " + collection.length + " items");
    },
    error: function() {
      return console.log("Something went wrong");
    }
  });

}).call(this);
