// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "backbone-relational", "TestModel"], function(Backbone, BackboneRelational, TestModel) {
    var TestModels;
    return TestModels = (function(_super) {

      __extends(TestModels, _super);

      function TestModels() {
        return TestModels.__super__.constructor.apply(this, arguments);
      }

      TestModels.prototype.model = TestModel;

      TestModels.prototype.localStorage = new Store("TestModels");

      return TestModels;

    })(Backbone.Collection);
  });

}).call(this);
