// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Todo = (function(_super) {

    __extends(Todo, _super);

    function Todo() {
      return Todo.__super__.constructor.apply(this, arguments);
    }

    Todo.prototype.urlRoot = "/todos";

    Todo.prototype.defaults = {
      name: "",
      description: ""
    };

    return Todo;

  })(window.ViewFirstModel);

  window.Todos = (function(_super) {

    __extends(Todos, _super);

    function Todos() {
      return Todos.__super__.constructor.apply(this, arguments);
    }

    Todos.prototype.model = Todo;

    Todos.prototype.url = "/todos";

    return Todos;

  })(Backbone.Collection);

  window.allTodos = new Todos();

  allTodos.fetch({
    success: function(collection) {
      return console.log("There are now " + collection.length + " in the todos");
    },
    error: function(collection) {
      return console.log("There was a real bad error!");
    }
  });

}).call(this);
