// Generated by CoffeeScript 1.4.0
(function() {
  var BindHelpers, TemplatingSnippets, ViewFirst, ViewFirstModel,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ViewFirstModel = (function(_super) {

    __extends(ViewFirstModel, _super);

    ViewFirstModel.instances = {};

    function ViewFirstModel(attributes) {
      var instances, model;
      instances = this.constructor.instances;
      if ((attributes != null ? attributes.id : void 0) != null) {
        if (instances[attributes.id] != null) {
          console.log("returning an existing instance");
          model = instances[attributes.id];
          Backbone.Model.apply(model, arguments);
          return model;
        }
        instances[attributes.id] = this;
      }
      Backbone.Model.apply(this, arguments);
    }

    return ViewFirstModel;

  })(Backbone.Model);

  TemplatingSnippets = (function() {

    function TemplatingSnippets() {}

    TemplatingSnippets.add = function(viewFirst) {
      viewFirst.addSnippet("surround", this.surroundSnippet);
      return viewFirst.addSnippet("embed", this.embedSnippet);
    };

    TemplatingSnippets.surroundSnippet = function(viewFirst, node, argumentMap) {
      var at, nodes, surroundingContent, surroundingName, surroundingView;
      nodes = node.contents();
      console.log("_surroundSnippet invoked with " + node);
      surroundingName = argumentMap['with'];
      at = argumentMap['at'];
      surroundingView = viewFirst.findView(surroundingName);
      if (surroundingView == null) {
        throw "Unable to find surrounding template '" + surroundingName + "'";
      }
      surroundingContent = $(surroundingView.getElement());
      if (at != null) {
        TemplatingSnippets.bind(surroundingContent, nodes, at);
      } else {
        TemplatingSnippets.bindParts(surroundingContent, nodes);
      }
      return surroundingContent;
    };

    TemplatingSnippets.bindParts = function(surroundingContent, nodes) {
      var at, child, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = nodes.length; _i < _len; _i++) {
        child = nodes[_i];
        at = $(child).attr("data-at");
        if (at != null) {
          _results.push(this.bind(surroundingContent, child.childNodes, at));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    TemplatingSnippets.bind = function(surroundingContent, html, at) {
      var bindElement;
      bindElement = surroundingContent.find("[data-bind-name='" + at + "']");
      return bindElement.replaceWith(html);
    };

    TemplatingSnippets.embedSnippet = function(viewFirst, html, argumentMap) {
      var embeddedView, templateName;
      templateName = argumentMap['template'];
      embeddedView = viewFirst.findView(templateName);
      if (embeddedView == null) {
        throw "Unable to find template to embed '" + templateName + "'";
      }
      return $(embeddedView.getElement()).clone();
    };

    return TemplatingSnippets;

  }).call(this);

  BindHelpers = (function() {

    function BindHelpers() {}

    BindHelpers.prototype.bindCollection = function(collection, parentNode, func) {
      var $parent, addChild, boundModels, context, removeChild,
        _this = this;
      boundModels = {};
      addChild = function(modelToAdd) {
        var childNode;
        console.log("adding child");
        childNode = func(modelToAdd);
        _this.bindTextNodes(childNode, modelToAdd);
        _this.bindNodeValues(childNode, modelToAdd);
        $parent.append(childNode);
        return boundModels[modelToAdd] = childNode;
      };
      removeChild = function(modelToRemove) {
        var childNode;
        childNode = boundModels[modelToRemove];
        $(childNode).detach();
        return delete boundModels[modelToRemove];
      };
      $parent = $(parentNode);
      context = uniqueNumber();
      console.log("context = " + context);
      collection.each(function(model) {
        return addChild(model);
      });
      collection.on("add", (function(newModel) {
        return addChild(newModel);
      }), context);
      collection.on("destroy", (function(removedModel) {
        return removeChild(removedModel);
      }), context);
      return collection.on("reset", (function() {
        collection.off(null, null, context);
        return _this.bindCollection(collection, parentNode, func);
      }), context);
    };

    BindHelpers.prototype.bindNodeToModel = function(node, model, func) {
      var currentBinding;
      currentBinding = node["currentBinding"];
      if (currentBinding != null) {
        model.off("change", currentBinding);
      }
      return node["currentBinding"] = model.on("change", func);
    };

    BindHelpers.prototype.bindTextNodes = function(node, model) {
      var _this = this;
      return BindHelpers.doForNodeAndChildren(node, function(node) {
        var doReplacement, getReplacementText, originalText;
        getReplacementText = function(nodeText, model) {
          var removeSurround;
          removeSurround = function(str) {
            return str.match(/[^#{}]+/);
          };
          return nodeText.replace(/#\{[^\}]*\}/g, function(match) {
            return model.get(removeSurround(match));
          });
        };
        originalText = node.text();
        doReplacement = function() {
          var replacementText;
          replacementText = getReplacementText(originalText, model);
          return node.get(0).nodeValue = replacementText;
        };
        if (node.get(0).nodeType === ViewFirst.TEXT_NODE && node.text().match(/#{.*}/)) {
          _this.bindNodeToModel(node, model, doReplacement);
          return doReplacement();
        }
      });
    };

    BindHelpers.prototype.addNamedBinding = function(name, event, $node, func) {
      var key;
      key = event + "." + name;
      $node.unbind(key);
      return $node.bind(key, func);
    };

    BindHelpers.prototype.bindNodeValues = function(node, model) {
      var _this = this;
      return BindHelpers.doForNodeAndChildren(node, function(aNode) {
        var property;
        property = aNode.attr("data-property");
        if (property != null) {
          _this.bindNodeToModel(aNode, model, function() {
            return aNode.val(model.get(property));
          });
          _this.addNamedBinding("updateModel", "blur", aNode, function() {
            model.set(property, aNode.val());
            return model.save();
          });
          return aNode.val(model.get(property));
        }
      });
    };

    BindHelpers.doForNodeAndChildren = function(node, func) {
      var childNode, _i, _len, _ref, _results;
      func(node);
      _ref = node.contents();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        childNode = _ref[_i];
        _results.push(BindHelpers.doForNodeAndChildren($(childNode), func));
      }
      return _results;
    };

    return BindHelpers;

  })();

  ViewFirst = (function(_super) {
    var uniqueNumber;

    __extends(ViewFirst, _super);

    ViewFirst.TEXT_NODE = 3;

    /*
        namedModelEventListeners contain a map of namedModel name to array of event handlers
    */


    function ViewFirst(indexView, views, namedModels, namedModelEventListeners, router, snippets) {
      this.indexView = indexView;
      this.views = views != null ? views : {};
      this.namedModels = namedModels != null ? namedModels : {};
      this.namedModelEventListeners = namedModelEventListeners != null ? namedModelEventListeners : {};
      this.router = router != null ? router : new ViewFirstRouter(this);
      this.snippets = snippets != null ? snippets : {};
      TemplatingSnippets.add(this);
    }

    uniqueNumber = function() {
      if (this.lastNumber != null) {
        return this.lastNumber++;
      } else {
        return this.lastNumber = 0;
      }
    };

    ViewFirst.prototype.initialize = function() {
      var _this = this;
      $('script[type="text/view-first-template"]').each(function(id, el) {
        var node, viewName;
        node = $(el);
        console.log("Loading script with id=" + (node.attr('name')));
        viewName = node.attr("name");
        _this.createView(viewName, node.html());
        return _this.router.addRoute(viewName, viewName === _this.indexView);
      });
      return Backbone.history.start();
    };

    ViewFirst.prototype.findView = function(viewId) {
      return this.views[viewId];
    };

    ViewFirst.prototype.renderView = function(viewId) {
      var rendered, view;
      this.currentView = viewId;
      view = this.findView(viewId);
      rendered = view.render();
      return $('body').html(rendered);
    };

    ViewFirst.prototype.navigate = function(viewId) {
      return Backbone.history.navigate(viewId, true);
    };

    ViewFirst.prototype.createView = function(viewId, content) {
      var view;
      view = new View(this, viewId, content);
      this.views[viewId] = view;
      return view;
    };

    ViewFirst.prototype.addSnippet = function(name, func) {
      return this.snippets[name] = func;
    };

    ViewFirst.prototype.setNamedModel = function(name, model, dontSerialize) {
      var eventListenerArray, func, oldModel, _i, _len, _results,
        _this = this;
      if (dontSerialize == null) {
        dontSerialize = false;
      }
      oldModel = this.namedModels[name];
      if (model != null) {
        this.namedModels[name] = model;
        model.constructor.bind("destroy", function() {
          return _this.setNamedModel(name, null);
        });
      } else {
        delete this.namedModels[name];
      }
      console.log("named model set");
      if (!dontSerialize) {
        this.router.updateState();
      }
      eventListenerArray = this.namedModelEventListeners[name];
      if (eventListenerArray != null) {
        _results = [];
        for (_i = 0, _len = eventListenerArray.length; _i < _len; _i++) {
          func = eventListenerArray[_i];
          _results.push(func(oldModel, model));
        }
        return _results;
      }
    };

    ViewFirst.prototype.addNamedModelEventListener = function(name, func) {
      var eventListenerArray;
      eventListenerArray = this.namedModelEventListeners[name];
      if (eventListenerArray == null) {
        eventListenerArray = [];
        this.namedModelEventListeners[name] = eventListenerArray;
      }
      return eventListenerArray.push(func);
    };

    return ViewFirst;

  })(BindHelpers);

  window.ViewFirst = ViewFirst;

  window.ViewFirstModel = ViewFirstModel;

}).call(this);
