// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ViewFirstModel = (function(_super) {

    __extends(ViewFirstModel, _super);

    ViewFirstModel.instances = {};

    function ViewFirstModel(attributes) {
      var instances, model;
      instances = this.constructor.instances;
      if ((attributes != null ? attributes.id : void 0) != null) {
        if (instances[attributes.id] != null) {
          console.log("returning an existing instance");
          model = instances[attributes.id];
          Backbone.Model.apply(model, arguments);
          return model;
        }
        instances[attributes.id] = this;
      }
      Backbone.Model.apply(this, arguments);
    }

    return ViewFirstModel;

  })(Backbone.Model);

  window.ViewFirst = (function() {
    var uniqueNumber;

    ViewFirst.TEXT_NODE = 3;

    /*
    
        namedModelEventListeners contain a map of namedModel name to array of event handlers
    */


    function ViewFirst(indexView, views, namedModels, namedModelEventListeners, namedBindings, router) {
      this.indexView = indexView;
      this.views = views != null ? views : {};
      this.namedModels = namedModels != null ? namedModels : {};
      this.namedModelEventListeners = namedModelEventListeners != null ? namedModelEventListeners : {};
      this.namedBindings = namedBindings != null ? namedBindings : {};
      this.router = router != null ? router : new ViewFirstRouter(this);
      this.snippets = {
        surround: ViewFirst._surroundSnippet,
        embed: ViewFirst._embedSnippet
      };
    }

    uniqueNumber = function() {
      if (this.lastNumber != null) {
        return this.lastNumber++;
      } else {
        return this.lastNumber = 0;
      }
    };

    ViewFirst.prototype.initialize = function() {
      var _this = this;
      $('script[type="text/view-first-template"]').each(function(id, el) {
        var node, viewName;
        node = $(el);
        console.log("Loading script with id=" + (node.attr('name')));
        viewName = node.attr("name");
        _this.createView(viewName, node.html());
        return _this.router.addRoute(viewName, viewName === _this.indexView);
      });
      return Backbone.history.start();
    };

    ViewFirst.prototype.findView = function(viewId) {
      return this.views[viewId];
    };

    ViewFirst.prototype.renderView = function(viewId) {
      var view;
      this.currentView = viewId;
      view = this.findView(viewId);
      return $('body').html(view.render());
    };

    ViewFirst.prototype.navigate = function(viewId) {
      return Backbone.history.navigate(viewId, true);
    };

    ViewFirst.prototype.createView = function(viewId, content) {
      var view;
      view = new View(this, viewId, content);
      this.views[viewId] = view;
      return view;
    };

    ViewFirst.prototype.addSnippet = function(name, func) {
      return this.snippets[name] = func;
    };

    ViewFirst.prototype.setNamedModel = function(name, model, dontSerialize) {
      var eventListenerArray, func, oldModel, _i, _len, _results,
        _this = this;
      if (dontSerialize == null) {
        dontSerialize = false;
      }
      oldModel = this.namedModels[name];
      if (model != null) {
        this.namedModels[name] = model;
        model.constructor.bind("destroy", function() {
          return _this.setNamedModel(name, null);
        });
      } else {
        delete this.namedModels[name];
      }
      console.log("named model set");
      if (!dontSerialize) {
        this.router.updateState();
      }
      eventListenerArray = this.namedModelEventListeners[name];
      if (eventListenerArray != null) {
        _results = [];
        for (_i = 0, _len = eventListenerArray.length; _i < _len; _i++) {
          func = eventListenerArray[_i];
          _results.push(func(oldModel, model));
        }
        return _results;
      }
    };

    ViewFirst.prototype.addNamedModelEventListener = function(name, func) {
      var eventListenerArray;
      eventListenerArray = this.namedModelEventListeners[name];
      if (eventListenerArray == null) {
        eventListenerArray = [];
        this.namedModelEventListeners[name] = eventListenerArray;
      }
      return eventListenerArray.push(func);
    };

    ViewFirst._surroundSnippet = function(viewFirst, node, argumentMap) {
      var at, nodes, surroundingContent, surroundingName, surroundingView;
      nodes = node.children;
      console.log("_surroundSnippet invoked with " + node);
      surroundingName = argumentMap['with'];
      at = argumentMap['at'];
      surroundingView = viewFirst.findView(surroundingName);
      if (surroundingView == null) {
        throw "Unable to find surrounding template '" + surroundingName + "'";
      }
      surroundingContent = $(surroundingView.getElement()).get();
      if (at != null) {
        ViewFirst._bind(surroundingContent, nodes, at);
      } else {
        ViewFirst._bindParts(surroundingContent, nodes);
      }
      return surroundingContent;
    };

    ViewFirst._bindParts = function(surroundingContent, nodes) {
      var at, child, _results;
      child = nodes[0];
      _results = [];
      while (child != null) {
        at = $(child).attr("data-at");
        if (at != null) {
          this._bind(surroundingContent, child.childNodes, at);
        }
        _results.push(child = child.nextSibling);
      }
      return _results;
    };

    ViewFirst._bind = function(surroundingContent, html, at) {
      var bindElement;
      bindElement = $(surroundingContent).find("[data-bind-name='" + at + "']");
      return bindElement.replaceWith(html);
    };

    ViewFirst._embedSnippet = function(viewFirst, html, argumentMap) {
      var embeddedView, templateName;
      templateName = argumentMap['template'];
      embeddedView = viewFirst.findView(templateName);
      if (embeddedView == null) {
        throw "Unable to find template to embed '" + templateName + "'";
      }
      return $(embeddedView.getElement()).clone().get();
    };

    ViewFirst.replaceNode = function(parent, nodeToReplace, nodeOrNodeList) {
      var convertToFlatArray, newNode, nextSibling, nodeArray, _fn, _i, _len,
        _this = this;
      convertToFlatArray = function(nodeList) {
        var addAllToArray, nodeArray;
        addAllToArray = function(nodeList, nodeArray) {
          var node, _i, _len, _results;
          _results = [];
          for (_i = 0, _len = nodeList.length; _i < _len; _i++) {
            node = nodeList[_i];
            _results.push((function(node) {
              if (_this.isNodeListOrArray(node)) {
                return addAllToArray(node, nodeArray);
              } else {
                return nodeArray.push(node);
              }
            })(node));
          }
          return _results;
        };
        nodeArray = [];
        addAllToArray(nodeList, nodeArray);
        return nodeArray;
      };
      if (this.isNodeListOrArray(nodeOrNodeList)) {
        nodeArray = convertToFlatArray(nodeOrNodeList);
        nextSibling = nodeToReplace.nextSibling;
        _fn = function(newNode) {
          if (!_this.containsChild(parent, nextSibling)) {
            throw "nextSibling was not contained in parent";
          }
          return parent.insertBefore(newNode, nextSibling);
        };
        for (_i = 0, _len = nodeArray.length; _i < _len; _i++) {
          newNode = nodeArray[_i];
          _fn(newNode);
        }
        parent.removeChild(nodeToReplace);
        return nodeArray;
      } else {
        parent.replaceChild(nodeOrNodeList, nodeToReplace);
        return nodeOrNodeList;
      }
    };

    ViewFirst.isNodeListOrArray = function(nodeOrNodeList) {
      return nodeOrNodeList.toString() === '[object NodeList]' || nodeOrNodeList instanceof Array;
    };

    ViewFirst.containsChild = function(parent, child) {
      var contained, node, _fn, _i, _len, _ref;
      contained = !(child != null);
      _ref = parent.childNodes;
      _fn = function(node) {
        return contained = contained || node === child;
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        node = _ref[_i];
        _fn(node);
      }
      return contained;
    };

    ViewFirst.prototype.bindCollection = function(collection, parentNode, func) {
      var $parent, addChild, boundModels, context, removeChild,
        _this = this;
      boundModels = {};
      addChild = function(modelToAdd) {
        var childNode;
        console.log("adding child");
        childNode = func(modelToAdd);
        _this.bindTextNodes(childNode, modelToAdd);
        _this.bindNodeValues(childNode, modelToAdd);
        $parent.append(childNode);
        return boundModels[modelToAdd] = childNode;
      };
      removeChild = function(modelToRemove) {
        var childNode;
        childNode = boundModels[modelToRemove];
        $(childNode).detach();
        return delete boundModels[modelToRemove];
      };
      $parent = $(parentNode);
      context = uniqueNumber();
      console.log("context = " + context);
      collection.each(function(model) {
        return addChild(model);
      });
      collection.on("add", (function(newModel) {
        return addChild(newModel);
      }), context);
      collection.on("destroy", (function(removedModel) {
        return removeChild(removedModel);
      }), context);
      return collection.on("reset", (function() {
        collection.off(null, null, context);
        return _this.bindCollection(collection, parentNode, func);
      }), context);
    };

    ViewFirst.prototype.bindNodeToModel = function(node, model, func) {
      var currentBinding;
      currentBinding = node["currentBinding"];
      if (currentBinding != null) {
        model.off("change", currentBinding);
      }
      return node["currentBinding"] = model.on("change", func);
    };

    ViewFirst.prototype.bindTextNodes = function(node, model) {
      var _this = this;
      return ViewFirst.doForNodeAndChildren(node, function(node) {
        var doReplacement, getReplacementText, originalText;
        getReplacementText = function(nodeText, model) {
          var removeSurround;
          removeSurround = function(str) {
            return str.match(/[^#{}]+/);
          };
          return nodeText.replace(/#\{[^\}]*\}/g, function(match) {
            return model.get(removeSurround(match));
          });
        };
        originalText = node.nodeValue;
        doReplacement = function() {
          var replacementText;
          replacementText = getReplacementText(originalText, model);
          return node.nodeValue = replacementText;
        };
        if (node.nodeType === ViewFirst.TEXT_NODE && node.nodeValue.match(/#{.*}/)) {
          _this.bindNodeToModel(node, model, doReplacement);
          return doReplacement();
        }
      });
    };

    ViewFirst.prototype.addNamedBinding = function(name, event, $node, func) {
      var key;
      key = event + "." + name;
      $node.unbind(key);
      return $node.bind(key, func);
    };

    ViewFirst.prototype.bindNodeValues = function(node, model) {
      var _this = this;
      return ViewFirst.doForNodeAndChildren(node, function(singleNode) {
        var jQNode, property;
        jQNode = $(singleNode);
        property = jQNode.attr("data-property");
        if (property != null) {
          _this.bindNodeToModel(singleNode, model, function() {
            return jQNode.val(model.get(property));
          });
          _this.addNamedBinding("updateModel", "blur", jQNode, function() {
            model.set(property, jQNode.val());
            return model.save();
          });
          return jQNode.val(model.get(property));
        }
      });
    };

    ViewFirst.doForNodeAndChildren = function(node, func) {
      var child, _results;
      func(node);
      child = node.firstChild;
      _results = [];
      while (child != null) {
        this.doForNodeAndChildren(child, func);
        _results.push(child = child.nextSibling);
      }
      return _results;
    };

    return ViewFirst;

  }).call(this);

}).call(this);
