// Generated by CoffeeScript 1.4.0
(function() {

  require(["ViewFirst", "jquery", "DogModel", "DogModels"], function(ViewFirst, $, DogModel, DogModels) {
    return $(function() {
      var addTerry, alsatian, collie, dogRow, dogs, removeColin, viewFirst;
      viewFirst = new ViewFirst("main");
      collie = new DogModel();
      collie.set("name", "Colin");
      collie.set("colour", "Brown");
      collie.set("breed", "Collie");
      collie.set("height", "16 inches");
      alsatian = new DogModel();
      alsatian.set("name", "Alfie");
      alsatian.set("colour", "Black");
      alsatian.set("breed", "Alsatian");
      alsatian.set("height", "20 inches");
      alsatian.save();
      collie.save();
      dogs = new DogModels();
      dogs.add(collie);
      dogs.add(alsatian);
      dogRow = function(viewFirst, node, argMap) {
        var createNode;
        createNode = function(dog) {
          return node.clone();
        };
        viewFirst.bindCollection(dogs, node.parent(), createNode);
        return null;
      };
      addTerry = function(viewFirst, node, argMap) {
        node.click(function() {
          var terry;
          terry = new DogModel();
          terry.set("name", "Terry");
          terry.set("colour", "Grey");
          terry.set("breed", "Terrier");
          terry.set("height", "5 inches");
          return dogs.add(terry);
        });
        return node;
      };
      removeColin = function(viewFirst, node, argMap) {
        node.click(function() {
          return dogs.remove(collie);
        });
        return node;
      };
      viewFirst.addSnippet("dogRow", dogRow);
      viewFirst.addSnippet("addTerry", addTerry);
      viewFirst.addSnippet("removeColin", removeColin);
      return viewFirst.initialize();
    });
  });

}).call(this);
