// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone-relational", "backbone.localStorage", "backbone"], function(BackboneRelational, BackboneLocalStorage, Backbone) {
    return window.Collar = (function(_super) {

      __extends(Collar, _super);

      function Collar() {
        return Collar.__super__.constructor.apply(this, arguments);
      }

      Collar.prototype.localStorage = new Store("DogModels");

      Collar.prototype.defaults = {
        colour: ""
      };

      return Collar;

    })(Backbone.RelationalModel);
  });

}).call(this);
