// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["DogModel", "backbone.localStorage", "backbone"], function(DogModel, BackboneLocalStorage, Backbone) {
    return window.DogModels = (function(_super) {

      __extends(DogModels, _super);

      function DogModels() {
        return DogModels.__super__.constructor.apply(this, arguments);
      }

      DogModels.prototype.model = DogModel;

      DogModels.prototype.localStorage = new Store("DogModels");

      return DogModels;

    })(Backbone.Collection);
  });

}).call(this);
