// Generated by CoffeeScript 1.4.0
(function() {

  require(["ViewFirst", "jquery"], function(ViewFirst, $) {
    return $(function() {
      var viewFirst;
      viewFirst = new ViewFirst("main");
      return viewFirst.initialize();
    });
  });

}).call(this);
