// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["ViewFirstModel", "backbone.localStorage"], function(ViewFirstModel, BackboneLocalStorage) {
    var TestModel;
    TestModel = (function(_super) {

      __extends(TestModel, _super);

      function TestModel() {
        return TestModel.__super__.constructor.apply(this, arguments);
      }

      TestModel.prototype.localStorage = new Store("TestModels");

      TestModel.prototype.url = "/";

      TestModel.prototype.defaults = {
        testProperty: ""
      };

      return TestModel;

    })(ViewFirstModel);
    return window.TestModel = TestModel;
  });

}).call(this);
