// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var changeCollarColour, changeColour, collar, collie, dogWithCollar, nestedDog, simpleBind, updateDogsName, viewFirst;
    viewFirst = new ViewFirst("main");
    collie = new DogModel();
    collie.set("name", "Alfie");
    collie.set("colour", "Brown");
    collie.set("breed", "Collie");
    collie.set("height", "16 inches");
    collie.save();
    simpleBind = function(viewFirst, node, argMap) {
      viewFirst.bindNodes(node, collie);
      return node;
    };
    updateDogsName = function(viewFirst, node, argMap) {
      updateDogsName = function() {
        return collie.set("name", "Donald");
      };
      $(node).click(updateDogsName);
      return node;
    };
    changeColour = function(viewFirst, node, argMap) {
      viewFirst.bindNodeValues(node, collie);
      return node;
    };
    nestedDog = new DogModel;
    collar = new Collar;
    collar.set("colour", "red");
    nestedDog.set("collar", collar);
    dogWithCollar = function(viewFirst, node, argMap) {
      viewFirst.bindNodes(node, nestedDog);
      return node;
    };
    changeCollarColour = function(viewFirst, node, argMap) {
      node.click(function() {
        return collar.set("colour", "blue");
      });
      return node;
    };
    viewFirst.addSnippet("simpleBind", simpleBind);
    viewFirst.addSnippet("updateDogsName", updateDogsName);
    viewFirst.addSnippet("changeColour", changeColour);
    viewFirst.addSnippet("dogWithCollar", dogWithCollar);
    viewFirst.addSnippet("changeCollarColour", changeCollarColour);
    return viewFirst.initialize();
  });

}).call(this);
