// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var changeColour, collie, simpleBind, updateDogsName, viewFirst;
    viewFirst = new ViewFirst("main");
    collie = new DogModel();
    collie.set("name", "Alfie");
    collie.set("colour", "Brown");
    collie.set("breed", "Collie");
    collie.set("height", "16 inches");
    collie.save();
    simpleBind = function(viewFirst, node, argMap) {
      viewFirst.bindTextNodes(node, collie);
      return node;
    };
    updateDogsName = function(viewFirst, node, argMap) {
      updateDogsName = function() {
        return collie.set("name", "Donald");
      };
      $(node).click(updateDogsName);
      return node;
    };
    changeColour = function(viewFirst, node, argMap) {
      viewFirst.bindNodeValues(node, collie);
      return node;
    };
    viewFirst.addSnippet("simpleBind", simpleBind);
    viewFirst.addSnippet("updateDogsName", updateDogsName);
    viewFirst.addSnippet("changeColour", changeColour);
    return viewFirst.initialize();
  });

}).call(this);
