// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Collar = (function(_super) {

    __extends(Collar, _super);

    function Collar() {
      return Collar.__super__.constructor.apply(this, arguments);
    }

    Collar.prototype.localStorage = new Store("DogModels");

    Collar.prototype.defaults = {
      colour: ""
    };

    return Collar;

  })(Backbone.RelationalModel);

  window.DogModel = (function(_super) {

    __extends(DogModel, _super);

    function DogModel() {
      return DogModel.__super__.constructor.apply(this, arguments);
    }

    DogModel.prototype.localStorage = new Store("DogModels");

    DogModel.prototype.url = "/";

    DogModel.prototype.relations = [
      {
        type: Backbone.HasOne,
        key: 'collar',
        relatedModel: 'Collar'
      }
    ];

    DogModel.prototype.defaults = {
      name: "",
      colour: "",
      breed: "",
      height: ""
    };

    return DogModel;

  })(Backbone.RelationalModel);

  window.DogModels = (function(_super) {

    __extends(DogModels, _super);

    function DogModels() {
      return DogModels.__super__.constructor.apply(this, arguments);
    }

    DogModels.prototype.model = DogModel;

    DogModels.prototype.localStorage = new Store("DogModels");

    return DogModels;

  })(Backbone.Collection);

}).call(this);
