// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var clearNamedModel, namedModel1, namedModel2, setOriginalNamedModel, showNotifications, testModelCollection, updateNamedModel, viewFirst;
    viewFirst = new ViewFirst("main");
    namedModel1 = new TestModel();
    namedModel1.set("testProperty", "originalValue");
    namedModel1.set("id", 1);
    namedModel2 = new TestModel();
    namedModel2.set("testProperty", "newValue");
    namedModel2.set("id", 2);
    namedModel1.save();
    namedModel2.save();
    testModelCollection = new TestModels;
    testModelCollection.add(namedModel1);
    testModelCollection.add(namedModel2);
    setOriginalNamedModel = function(viewFirst, node, argMap) {
      var $node;
      $node = $(node);
      $node.click(function() {
        return viewFirst.setNamedModel("aName", namedModel1);
      });
      return node;
    };
    updateNamedModel = function(viewFirst, node, argMap) {
      var $node;
      $node = $(node);
      $node.click(function() {
        return viewFirst.setNamedModel("aName", namedModel2);
      });
      return node;
    };
    clearNamedModel = function(viewFirst, node, argMap) {
      var $node;
      $node = $(node);
      $node.click(function() {
        return viewFirst.setNamedModel("aName", null);
      });
      return node;
    };
    showNotifications = function(viewFirst, node, argMap) {
      var $node, newModelParagraph, oldModelParagraph;
      $node = $(node);
      oldModelParagraph = $node.find("p#oldModelParagraph");
      newModelParagraph = $node.find("p#newModelParagraph");
      viewFirst.addNamedModelEventListener("aName", function(oldModel, newModel) {
        oldModelParagraph.text(oldModel != null ? oldModel.get("testProperty") : "");
        return newModelParagraph.text(newModel != null ? newModel.get("testProperty") : "");
      });
      return node;
    };
    viewFirst.addSnippet("updateNamedModel", updateNamedModel);
    viewFirst.addSnippet("clearNamedModel", clearNamedModel);
    viewFirst.addSnippet("showNotifications", showNotifications);
    viewFirst.addSnippet("setOriginalNamedModel", setOriginalNamedModel);
    return viewFirst.initialize();
  });

}).call(this);
