// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var renderOtherView, viewFirst;
    viewFirst = new ViewFirst("routingHome");
    renderOtherView = function(viewFirst, node, argMap) {
      $(node).click(function() {
        return viewFirst.navigate("otherView");
      });
      return node;
    };
    viewFirst.addSnippet("renderOtherView", renderOtherView);
    return viewFirst.initialize();
  });

}).call(this);
