// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var incrementingNumber, number, simplyInvoke, upToTen, viewFirst;
    viewFirst = new ViewFirst("simplyInvoke");
    simplyInvoke = function(viewFirst, node, argMap) {
      node.text("Was Invoked");
      return node;
    };
    incrementingNumber = 1;
    number = function(viewFirst, node, argMap) {
      node.children("p").children("span").text(incrementingNumber++);
      return node;
    };
    upToTen = function(viewFirst, node, argMap) {
      var newSnippet, startingFrom;
      startingFrom = argMap["startingFrom"];
      newSnippet = startingFrom !== 10 ? "<span data-snippet=\"upToTen\" data-starting-from=\"" + (startingFrom + 1) + "\"></span>" : "";
      return $("<p>" + (startingFrom.toString()) + "</p>" + newSnippet);
    };
    viewFirst.addSnippet("simplyInvoke", simplyInvoke);
    viewFirst.addSnippet("upToTen", upToTen);
    viewFirst.addSnippet("number", number);
    return viewFirst.initialize();
  });

}).call(this);
