// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TestModel = (function(_super) {

    __extends(TestModel, _super);

    function TestModel() {
      return TestModel.__super__.constructor.apply(this, arguments);
    }

    TestModel.prototype.localStorage = new Store("TestModels");

    TestModel.prototype.url = "/";

    TestModel.prototype.defaults = {
      testProperty: ""
    };

    return TestModel;

  })(window.ViewFirstModel);

  window.TestModels = (function(_super) {

    __extends(TestModels, _super);

    function TestModels() {
      return TestModels.__super__.constructor.apply(this, arguments);
    }

    TestModels.prototype.model = TestModel;

    TestModels.prototype.localStorage = new Store("TestModels");

    return TestModels;

  })(Backbone.Collection);

}).call(this);
